/**
 * build.js — bundles partials/*.html into assets/js/partials.generated.js.
 *
 * index.html keeps one placeholder per section (<div data-include="header">);
 * assets/js/include.js swaps the placeholders for the bundled markup at
 * runtime. Bundling (instead of fetch()) keeps the page working when it is
 * opened straight from the file system. No dependencies: `node build.js`.
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const PARTIALS = path.join(__dirname, 'partials');
const PAGE = path.join(__dirname, 'index.html');
const OUT = path.join(__dirname, 'assets', 'js', 'partials.generated.js');

const files = fs.readdirSync(PARTIALS).filter((file) => file.endsWith('.html')).sort();
const names = files.map((file) => file.replace(/\.html$/, ''));

// Every placeholder in index.html must have a partial, and every partial should be used.
const page = fs.readFileSync(PAGE, 'utf8');
const used = Array.from(page.matchAll(/data-include="([^"]+)"/g), (m) => m[1]);
const missing = used.filter((name) => !names.includes(name));
if (missing.length) {
  throw new Error('index.html includes partials that do not exist: ' + missing.join(', '));
}
const unused = names.filter((name) => !used.includes(name));
if (unused.length) {
  console.warn('Warning: partials not referenced by index.html: ' + unused.join(', '));
}

const escapeTemplate = (html) => html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const entries = files.map((file, i) => {
  const html = fs.readFileSync(path.join(PARTIALS, file), 'utf8').trim();
  return `    '${names[i]}': \`\n${escapeTemplate(html)}\n\``;
});

const output = [
  '/**',
  ' * partials.generated.js — GENERATED by build.js from partials/*.html. Do not edit;',
  ' * change the HTML files in partials/ and run `node build.js`.',
  ' */',
  '(function (ns) {',
  "  'use strict';",
  '  ns.partials = {',
  entries.join(',\n'),
  '  };',
  '})(window.ArtisanShop = window.ArtisanShop || {});',
  ''
].join('\n');

fs.writeFileSync(OUT, output);
console.log(`Wrote ${path.relative(__dirname, OUT)}: ${files.length} partials, ${output.length.toLocaleString()} bytes`);
